export const GET_USER = "GET_USER"
export const SET_USER = "SET_USER"
export const LOG_OUT_USER = "LOG_OUT_USER"
export const GET_USERS = "GET_USERS"
export const GET_MEDS = "GET_MEDS"
export const GET_MED = "GET_MED"
export const DELETE_MED = "DELETE_MED"